### PR TITLE
Fix tooltip location

### LINKED ISSUE #89: [UI] Tooltip location issue
The chart tooltip element is nested within a bunch of elements, so the whole `position: absolute` + coordinates thing isn't working well. It's way off on a big monitor. The tooltip element should be moved up in the hierarchy. Maybe it can just be a child of `body`?

### PR DESCRIPTION
**Pull request by Preetam**
Closes #89.

### CODE REVIEW

File: ui/js/Chart.js [hunk 1]
```diff
@@ -86,11 +86,15 @@ var Chart = function(chartState) {
             return getValue(b) - getValue(a);
           });
 
+          console.log(d3.event.pageX, d3.event.pageY)
```
Comment (Preetam) [inline ui/js/Chart.js]: Remove

File: ui/js/Chart.js [hunk 2]
```diff
@@ -86,11 +86,15 @@ var Chart = function(chartState) {
...
+
           var tooltip = d3.select(document).select(".chart-tooltip");
           tooltip.html(hoverDate)
             .style("position", "absolute")
             .style('display', 'block')
-            .style('left', d3.event.pageX + "px")
+            .style('margin', '0')
```
Comment (Preetam) [inline ui/js/Chart.js]: Move to CSS if necessary.

File: ui/js/Chart.js [hunk 3]
```diff
@@ -86,11 +86,15 @@ var Chart = function(chartState) {
...
+            .style('padding ', '0')
```
Comment (Preetam) [inline ui/js/Chart.js]: Same.

**Comment by Preetam** [comment]
Oh man, so glad I added build.sh :D.
